# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TealiumFirebaseExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumFirebaseExample
  pod 'TealiumFirebase', '0.0.2'
  pod 'tealium-swift/TealiumLogger'
  pod 'tealium-swift/TealiumTagManagement'
  pod 'tealium-swift/TealiumAppData'
  pod 'tealium-swift/TealiumDeviceData'
  pod 'tealium-swift/TealiumLifecycle'

end
